//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; D:\Insturmentacion 1C2019\Instrumentacion\Practica especial\PIDDRIVER.py
///  Source class: FLOWPIDDriver
///  Generation timestamp: 2019-06-18T18:43:32.068134
///  Class code hash: b4513fff6bb16d2ee86ec4e6995533d4e153bd09
///
/////////////////////////////////////////////////////////////

#ifndef inodriver_user_h
#define inodriver_user_h

void user_setup();
void user_loop();
float get_Kp(); 
int set_Kp(float); 
float get_Ki(); 
int set_Ki(float); 
float get_Set_Point(); 
int set_Set_Point(float); 
float get_Kd(); 
int set_Kd(float); 
float get_Pump_Flow(int); 
int set_Pump_Flow(int, float); 
int get_Control_Loop_enabled(); 
int set_Control_Loop_enabled(int); 
float get_Flow(); 
int set_Flow(float); 


#endif // inodriver_user_h