//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> DO NOT CHANGE <<<<
////
/// 
///  Filename; D:\Documentos\Licenciatura en Física\Laboratorios\Instrumentacion\Instrumentacion\Practica especial\V ersion 3.0\PIDDRIVER.py
///  Source class: FLOWPIDDriver
///  Generation timestamp: 2019-07-25T19:30:32.518211
///  Class code hash: b4513fff6bb16d2ee86ec4e6995533d4e153bd09
///
/////////////////////////////////////////////////////////////

#ifndef inodriver_bridge_h
#define inodriver_bridge_h

#include <Arduino.h>

#include "SerialCommand.h"

#include "inodriver_user.h"

const char COMPILE_DATE_TIME[] = __DATE__ " " __TIME__;

void ok();
void error(const char*);
void error_i(int);
void bridge_loop();
void bridge_setup();

void getInfo();
void unrecognized(const char *);
void wrapperGet_PF1(); 
void wrapperSet_PF1(); 
void wrapperGet_PF2(); 
void wrapperSet_PF2(); 
void wrapperGet_KD(); 
void wrapperSet_KD(); 
void wrapperGet_FV(); 
void wrapperGet_SP(); 
void wrapperSet_SP(); 
void wrapperGet_CLENABLE(); 
void wrapperSet_CLENABLE(); 
void wrapperGet_KP(); 
void wrapperSet_KP(); 
void wrapperGet_LI(); 
void wrapperSet_LI(); 


#endif // inodriver_bridge_h