//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; D:\Documentos\Licenciatura en Física\Laboratorios\Instrumentacion\Instrumentacion\Practica especial\V ersion 3.0\PIDDRIVER.py
///  Source class: FLOWPIDDriver
///  Generation timestamp: 2019-07-26T13:49:27.879974
///  Class code hash: b4513fff6bb16d2ee86ec4e6995533d4e153bd09
///
/////////////////////////////////////////////////////////////

#ifndef inodriver_user_h
#define inodriver_user_h

void user_setup();
void user_loop();
float get_SP(); 
int set_SP(float); 
float get_PF1(); 
int set_PF1(float); 
float get_KD(); 
int set_KD(float); 
float get_FV(); 
int get_CLEN(); 
int set_CLEN(int); 
float get_KI(); 
int set_KI(float); 
float get_PF2(); 
int set_PF2(float); 
float get_KP(); 
int set_KP(float); 


#endif // inodriver_user_h